version: '3.9'
services:
  redis:
    image: redis:7.2
    container_name: redis-for-stampede
    ports:
      - "6500:6379"
    command: ["redis-server", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - my-network

  mysql:
    image: mysql:8.0
    container_name: mysql-for-stampede
    ports:
      - "7777:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cache_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - my-network
    volumes:
      - mysql_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus-for-stampede
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my-network

  grafana:
    image: grafana/grafana:10.1.5
    container_name: grafana-for-stampede
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - my-network

  redis-exporter:
    image: oliver006/redis_exporter:v1.55.0
    container_name: redis-exporter-for-stampede
    depends_on:
      - redis
    command: ["--redis.addr=redis://redis:6379"]
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data:
