server:
  port: 8080

spring:
  application:
    name: cache-stampede-test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:7777/cache_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6500
      timeout: 2000

logging:
  level:
    root: INFO
    study.cache_stampede_test: DEBUG

redisson:
    address: redis://localhost:6500
    connectionPoolSize: 16
    connectionMinimumIdleSize: 4