server:
  port: 8080

spring:
  application:
    name: cache-stampede-demo

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: localhost
      timeout: 2000
      port: 6500

logging:
  level:
    root: INFO
    com.example.cache_stampede: DEBUG

redisson:
  address: redis://localhost:6500
  connectionPoolSize: 16
  connectionMinimumIdleSize: 4
